on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make archive
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: exc.tar.gz
